// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mnjiswsurusyrnvprlod.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1uamlzd3N1cnVzeXJudnBybG9kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyNjYzNTUsImV4cCI6MjA2Mjg0MjM1NX0.p_amNa3XSYFzQuxBEn6sfMgPHXRAAv2FTBNSNkp-V-M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);