
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qljjmugtmzaxvoahwskg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFsamptdWd0bXpheHZvYWh3c2tnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0NDMyMTgsImV4cCI6MjA2MzAxOTIxOH0.5zqSWdXcT2AowItnPkwFssIqi6kZM-bFU5hE6slIswI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storageKey: 'organimarket-auth'
  }
});
